name: "Release Builds"
on:
  push:
    branches:
      - dev
      - release-*
      - refs/tags/*

    ##############################################################################
    #                                                                            #
    #    These sections must be synchronized with 'paths' in full-ci-dummy.yml   #
    #                                                                            #
    ##############################################################################

  pull_request:
    branches:
      - '*'  # must quote since "*" is a YAML reserved character; we want a string

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linux:
    uses: ./.github/workflows/ci-manylinux.yml
    with:
      bootstrap_args: '--enable=azure'